-- AlterTable
ALTER TABLE `cita` MODIFY `fechaHora` TIMESTAMP(0) NOT NULL,
    MODIFY `fechaCreacion` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0);

-- AlterTable
ALTER TABLE `consultorio` MODIFY `fechaCreacion` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0);

-- AlterTable
ALTER TABLE `historialtest` MODIFY `fechaCompletado` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0);

-- AlterTable
ALTER TABLE `informacion_sociodemografica` MODIFY `fechaCreacion` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    MODIFY `fechaActualizacion` TIMESTAMP(0) NOT NULL;

-- AlterTable
ALTER TABLE `informacionusuario` MODIFY `fechaNacimiento` TIMESTAMP(0) NOT NULL,
    MODIFY `fechaCreacion` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    MODIFY `fechaActualizacion` TIMESTAMP(0) NOT NULL;

-- AlterTable
ALTER TABLE `practicante` MODIFY `fechaCreacion` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0);

-- AlterTable
ALTER TABLE `registrocitas` MODIFY `fechaHora` TIMESTAMP(0) NOT NULL,
    MODIFY `fechaCreacion` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0);

-- AlterTable
ALTER TABLE `rolchat` MODIFY `createdAt` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    MODIFY `updatedAt` TIMESTAMP(0) NOT NULL;
